# .sops.yaml
creation_rules:
  - path_regex: "^\\.env(\\..*)?$"
    age: >-
      age19c40zf7qel4dnnx30gvwnvtk56fg9lkg2rz9xukj9fzjj02qzguqae4h86,
      age1gsg9hdzgu7ddnahdgpuy3mf4ycekd0zqeqem8dj7pqhqkeq7n3hstvzgvj,
      age14nrkvrrgfamu9cn50w5mc3y3s44e9aep7el5na9zq78ks3zyjgustcjhdk
